### ISSUE TITLE
Can't  refresh page twice when session.auto_start set 1 in php.ini

### ISSUE THREAD

**Issue by kalecgos0616** [panique/php-long-polling#6]
Tested system: ubuntu/arch linux + apache

step:
copy index.html to client.php ( only php file can reproduce )

I can't refresh client/client.php at second time when session.auto_start=1 in php.ini

I resolve it after add session_write_close() or session_commit() in server.php

relative issue:
http://stackoverflow.com/questions/13213396/no-reply-when-using-flush-session-cookies-and-long-execution-time

I'm glad you read my report. Sorry for my poor English.

**Comment by panique** [comment]
Hey, can you say what is the default value for `session.auto_start` in php.ini (i dont have the possibility to check this right now) ?

**Comment by kalecgos0616** [comment]
zero.
